# Generated by Django 4.2.2 on 2024-09-08 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.CharField(max_length=100)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='static/images')),
            ],
        ),
        migrations.AddField(
            model_name='userpermissionassign',
            name='branch',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='branch_permissions', to='api.branch'),
            preserve_default=False,
        ),
    ]
