# Generated by Django 4.2.2 on 2024-09-11 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_newuser_groups_newuser_user_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtpMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.IntegerField(unique=True)),
                ('otp', models.IntegerField(default=0)),
                ('validated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Otp sms',
                'verbose_name_plural': 'SMSs OTPs',
                'db_table': 'OTP_SMS',
            },
        ),
        migrations.RemoveField(
            model_name='branch',
            name='picture',
        ),
        migrations.AddField(
            model_name='branch',
            name='partner_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='branch',
            name='partner_percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='branch',
            name='telephone',
            field=models.IntegerField(default=37419848, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='level',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('COACH', 'COACH'), ('PARENT', 'PARENT')], max_length=100),
        ),
        migrations.CreateModel(
            name='Branch_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='static/images')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branche_image', to='api.branch')),
            ],
        ),
    ]
