# Generated by Django 4.2.2 on 2024-09-11 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_otpmail_remove_branch_picture_branch_partner_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='telephone',
            field=models.IntegerField(null=True),
        ),
    ]
